### PR TITLE
fix-infobox-title-text-size

### PR DESCRIPTION
**Pull request by rushicruk**
Change to h3 to h4 for better UI/UX. h3 looks too big :(

### CODE REVIEW

**Comment by rcf-cruk** [comment]
@rushicruk Can the size of the H3 not be adjusted to the size it should be?  Perhaps by overriding the theme?  Level headings aren't really supposed to be used based on their size, they are semantic and define levels in the text.  So changing it to suit the size doesn't seem right to me.

**Comment by Develliot** [comment]
> @rushicruk Can the size of the H3 not be adjusted to the size it should be? Perhaps by overriding the theme? Level headings aren't really supposed to be used based on their size, they are semantic and define levels in the text. So changing it to suit the size doesn't seem right to me.

For this reason because you don't know where it's going to be used in the document may be it should always be h2 not h3, because if there isn't an h2 on the document it will throw and a11y warning, and being an info box this content should be quite self contained. I don't think it warrants an article because it's probably content related other things on the page

**Comment by rushicruk** [comment]
> > @rushicruk Can the size of the H3 not be adjusted to the size it should be? Perhaps by overriding the theme? Level headings aren't really supposed to be used based on their size, they are semantic and define levels in the text. So changing it to suit the size doesn't seem right to me.
> 
> For this reason because you don't know where it's going to be used in the document may be it should always be h2 not h3, because if there isn't an h2 on the document it will throw and a11y warning, and being an info box this content should be quite self contained. I don't think it warrants an article because it's probably content related other things on the page

What you suggest here @Develliot ? happy to do changes :)

**Comment by samkio** [comment]
> > @rushicruk Can the size of the H3 not be adjusted to the size it should be? Perhaps by overriding the theme? Level headings aren't really supposed to be used based on their size, they are semantic and define levels in the text. So changing it to suit the size doesn't seem right to me.
> 
> For this reason because you don't know where it's going to be used in the document may be it should always be h2 not h3, because if there isn't an h2 on the document it will throw and a11y warning, and being an info box this content should be quite self contained. I don't think it warrants an article because it's probably content related other things on the page

Would one option be that the header level should be provided as a property to InfoBox (as it is for Heading?)

**Comment by rushicruk** [comment]
> > > @rushicruk Can the size of the H3 not be adjusted to the size it should be? Perhaps by overriding the theme? Level headings aren't really supposed to be used based on their size, they are semantic and define levels in the text. So changing it to suit the size doesn't seem right to me.
> > 
> > 
> > For this reason because you don't know where it's going to be used in the document may be it should always be h2 not h3, because if there isn't an h2 on the document it will throw and a11y warning, and being an info box this content should be quite self contained. I don't think it warrants an article because it's probably content related other things on the page
> 
> Would one option be that the header level should be provided as a property to InfoBox (as it is for Heading?)

I think this is very good!! Any thoughts on this @Develliot

**Comment by Develliot** [comment]
Just clocked this has as="p" so it is always being cast as a paragraph tag
there should be no heading hierarchy issues here, it just takes the styling of h3 and turns it into a P 

my bad

**Review by Develliot — APPROVED** [review]

**Pull request merged**
