### PR TITLE
302 datefield required

### PR DESCRIPTION
**Pull request by Develliot**

### CODE REVIEW

**Comment by dhwani07** [comment]
Screen Reader unable to recognise required (Chrome /Firefox)

**Comment by Develliot** [comment]
Interesting mac os screen reader chrome reads the label and says the text field is required

**Comment by dhwani07** [comment]
Just retested with NVDA for windows screen reader , it works fine -the screen reader for chrome plugin does not read the label.

**Comment by Develliot** [comment]
fixes #302

**Pull request merged**
